name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - ".github/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    name: 🚀 Test, Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository @master
        uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: 🔎 Test
        run: npm test

      - name: 🔧 Build
        run: npm run build

      - name: 🚀 Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./build

  notifyDiscord:
    needs: deploy
    name: 📢 Notify on Discord
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Conclusion
        uses: technote-space/workflow-conclusion-action@v2

      - name: Notify Success
        if: env.WORKFLOW_CONCLUSION == 'success'
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.WEBHOOK_URL }}
          username: "${{ github.workflow }}"
          avatar-url: "https://media.discordapp.net/attachments/857447804977152000/894758305690452039/success_kid.png"
          title: "✔️ Deploy run #${{ github.run_number }} status: SUCCESS!"
          description: "🌐 [Visit the site](https://shirokatake.github.io/ytdl-frontend/)."
          include-details: "false"
          color-success: "#2eb886"

      - name: Notify Cancelled
        if: env.WORKFLOW_CONCLUSION == 'cancelled'
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.WEBHOOK_URL }}
          username: "${{ github.workflow }}"
          avatar-url: "https://media.discordapp.net/attachments/821500555696013343/925737666685837353/Blank-Nut-Button.png"
          title: "✖️ Deploy run #${{ github.run_number }} status: CANCELLED . . ."
          description: "Click the link above to view details on GitHub."
          include-details: "false"
          color-cancelled: "#ffd513"

      - name: Notify Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.WEBHOOK_URL }}
          username: "${{ github.workflow }}"
          avatar-url: "https://media.discordapp.net/attachments/857447804977152000/894760486439125042/explosion.png"
          title: "❌ Deploy run #${{ github.run_number }} status: FAILED . . ."
          description: "Click the link above to view details on GitHub."
          include-details: "false"
          color-failure: "#a30200"
