name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: 🚀 Test, Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository @master
        uses: actions/checkout@v2

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: 🔎 Test
        run: npm test

      - name: 🔧 Build
        run: npm run build

      - name: 🚀 Deploy
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./build
